 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/react:$COMMIT_SHA', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/react:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'react'
   - '--image'
   - 'gcr.io/$PROJECT_ID/react:$COMMIT_SHA'
   - '--region'
   - 'us-central1'
   - --platform"
   -  'managed'
   - --port
   - '80'
   - --allow-unauthenticated

 images:
 - 'gcr.io/$PROJECT_ID/react:$COMMIT_SHA'